# Generated by Django 3.1.7 on 2021-10-13 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20211013_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='liker_com', to=settings.AUTH_USER_MODEL),
        ),
    ]
